### PR TITLE
bug_76: fix issue with recorded ts

### LINKED ISSUE #76: add correct recorded timestamp to parquet files
currently the parquet files produced can have a recorded timestamp if "recorded" is added to config. currently the recorded timestamp stems from the UDA entities received, but should really be a recorded timestamp from when the parquet is created. 

If a record is added to a parquet, and the stream is reset to begin from the start, you will end up with two records with the same id and recorded timestamp. it then becomes hard to filter in the latest record from the list of parquet files.

to handle this it would be nice to have the recorded timestamp created when the parquet is created, and if there are two entities in the same batch, then the recorded should be shifted to not have colliding recorded timestamps.

this will avoid having colliding recorded timestamps when either the stream is reset, or the schema for the parquet has changed and you will have to reset.

### PR DESCRIPTION
**Pull request by ashmanto**
closes #76

### CODE REVIEW

File: internal/encoder/parquet.go [hunk 1]
```diff
@@ -55,11 +56,23 @@ func (enc *ParquetEncoder) Write(entities []*uda.Entity) (int, error) {
...
 	for _, e := range entities {
 		props := uda.StripProps(e)
 		refs := uda.StripRefs(e)
 		row := make(map[string]interface{})
+
+		recordId := e.ID
+		if recordId != "" {
+			if _, exists := seenIds[recordId]; exists {
+				// duplicate id in same batch
+				now = fmt.Sprintf("%d", time.Now().UTC().UnixNano())
```
Comment (gra-moore) [inline internal/encoder/parquet.go:72]: i think you need a sleep in here for shortest allowed period to ensure the clock moves along.

**Review by gra-moore — CHANGES_REQUESTED** [review]

File: internal/encoder/parquet.go (hunk 1 above)
Comment (ashmanto) [reply internal/encoder/parquet.go:72]: sleep added before new unix timestamp is created

**Review by gra-moore — APPROVED** [review]
